site_name: MimePost Docs
nav:
- Home: 'index.md'
- Getting Started: 'getting_started.md'
- User Guide:
    - 'Getting Started': 'getting_started.md'
    - 'Sandbox': 'sandbox.md'
    - 'SMTP': 'smtp.md'
    - 'API': 'api.md'
    - 'Webhooks': 'webhooks.md'
    - Integration : 
        - 'SDK' : 'integration.md'
          #- 'PHP Curl (example)' : 'php_curl.md'
        - 'Zapier' : 'zapier.md'
    - 'Custom Data': 'custom_data.md'
theme: readthedocs
